name: Deploy API with Deno Deploy
on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # -> Needed for auth with Deno Deploy
      contents: read    # -> Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Upload API to Deno Deploy
        uses: denoland/deployctl@v1
        env:
          # Setting an environment variables
          EXCHANGE_RATES_API: ${{ vars.EXCHANGE_RATES_API }}
          EXCHANGE_RATES_API_FALLBACK: ${{ vars.EXCHANGE_RATES_API_FALLBACK }}
        with:
          project: "currency-exchange-rates"
          entrypoint: "app.ts"
          root: "server"
          include: |
            deno.json
            app.ts
            processData.ts
            types.ts
            jsons/
